apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-asc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: opa-asc-proxy
  template:
    metadata:
      labels:
        run: opa-asc-proxy
    spec:
      containers:
      - image: sozercan/opa-asc-proxy:latest
        imagePullPolicy: Always
        name: opa-asc-proxy
        env:
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: azcred
              key: subscriptionid
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azcred
              key: clientid
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azcred
              key: clientsecret
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azcred
              key: tenantid
        ports:
        - containerPort: 8090
          protocol: TCP
      restartPolicy: Always
